import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Home,Compass,Plus,Radio,User,Heart,MessageCircle,Share2,Upload,LogIn,LogOut,X,BarChart3,Users,Gift} from 'lucide-react';
import {supabase} from './supabase';
import './styles.css';

function App(){
 const [session,setSession]=useState(null),[tab,setTab]=useState('home'),[posts,setPosts]=useState([]),[auth,setAuth]=useState(false),[live,setLive]=useState(false),[studio,setStudio]=useState(false);
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session));const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 const load=async()=>{if(!supabase)return;const {data}=await supabase.from('creator_posts').select('id,media_url,caption,views,likes,creator_id').eq('status','published').order('created_at',{ascending:false}).limit(30);setPosts(data||[])};
 useEffect(()=>{load()},[session]);
 return <div className="app"><header><div className="logo"><b>L</b><strong>Lking</strong></div><div className="header-actions">{session?<><button onClick={()=>setStudio(true)}><BarChart3/> Studio</button><button onClick={async()=>{await supabase.auth.signOut()}}><LogOut/></button></>:<button onClick={()=>setAuth(true)}><LogIn/> دخول</button>}</div></header>
 <main>{tab==='home'&&<Feed posts={posts} session={session} auth={()=>setAuth(true)}/>} {tab==='explore'&&<Explore posts={posts}/>} {tab==='live'&&<Live session={session} auth={()=>setAuth(true)} open={()=>setLive(true)}/>} {tab==='create'&&<Create session={session} auth={()=>setAuth(true)} reload={load} live={()=>setTab('live')}/>} {tab==='profile'&&<Profile session={session} auth={()=>setAuth(true)}/>}</main>
 <nav>{[[Home,'الرئيسية','home'],[Compass,'اكتشف','explore'],[Plus,'','create'],[Radio,'مباشر','live'],[User,'حسابي','profile']].map(([I,l,t],i)=><button className={i===2?'plus '+(tab===t?'active':''):(tab===t?'active':'')} onClick={()=>setTab(t)} key={t}><I/><small>{l}</small></button>)}</nav>
 {auth&&<Auth close={()=>setAuth(false)} done={s=>{setSession(s);setAuth(false)}}/>}{live&&<Broadcaster session={session} close={()=>setLive(false)}/>} {studio&&<Studio close={()=>setStudio(false)} session={session}/>}</div>
}
function Feed({posts,session,auth}){const [i,setI]=useState(0);const p=posts.length?posts[i%posts.length]:null;return <section className="feed" onWheel={e=>e.deltaY>15&&setI(x=>x+1)}>{p?<article className="post"><video src={p.media_url} controls playsInline/><div className="caption"><b>@creator</b><p>{p.caption}</p></div><div className="actions"><button onClick={async()=>{if(!session){auth();return}await supabase.from('post_likes').insert({user_id:session.user.id,post_id:p.id})}}><Heart/><span>{p.likes||0}</span></button><button><MessageCircle/><span>تعليقات</span></button><button><Share2/><span>مشاركة</span></button></div></article>:<div className="empty"><h1>مرحبًا بك في Lking</h1><p>ابدأ بنشر أول فيديو وبناء جمهورك.</p></div>}</section>}
function Explore({posts}){return <section className="page"><h1>اكتشف</h1><p>اكتشف أحدث محتوى صناع Lking.</p><div className="grid">{posts.map(p=><video key={p.id} src={p.media_url} muted playsInline controls/></div></section>}
function Live({session,auth,open}){const [rooms,setRooms]=useState([]);useEffect(()=>{if(!supabase)return;const get=()=>supabase.from('live_rooms').select('*').eq('status','live').order('started_at',{ascending:false}).then(({data})=>setRooms(data||[]));get();const c=supabase.channel('live').on('postgres_changes',{event:'*',schema:'public',table:'live_rooms'},get).subscribe();return()=>supabase.removeChannel(c)},[]);return <section className="page"><div className="row"><div><h1>البث المباشر</h1><p>شاهد وتفاعل مع صناع المحتوى لحظة بلحظة.</p></div><button className="primary" onClick={()=>session?open():auth()}><Radio/> ابدأ بثًا</button></div>{rooms.length?<div className="room-grid">{rooms.map(r=><div className="room" key={r.id}><span>LIVE</span><Radio/><b>{r.title}</b><small>{r.viewer_count} مشاهد</small></div>)}</div>:<div className="empty">لا يوجد بث مباشر الآن. كن أول من يبدأ.</div>}</section>}
function Create({session,auth,reload,live}){const [file,setFile]=useState(null),[caption,setCaption]=useState(''),[msg,setMsg]=useState('');const publish=async()=>{if(!session){auth();return}if(!file){setMsg('اختر فيديو أولًا');return}const path=`${session.user.id}/${crypto.randomUUID()}-${file.name}`;const {error:e}=await supabase.storage.from('videos').upload(path,file);if(e){setMsg(e.message);return}const {data}=supabase.storage.from('videos').getPublicUrl(path);const {error:x}=await supabase.from('creator_posts').insert({creator_id:session.user.id,media_url:data.publicUrl,caption,status:'published'});setMsg(x?x.message:'تم النشر بنجاح');if(!x)reload()};return <section className="create"><div><Upload size={50}/><h1>انشر على Lking</h1><label className="picker">اختيار فيديو<input type="file" accept="video/*" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><textarea value={caption} onChange={e=>setCaption(e.target.value)} placeholder="اكتب وصف الفيديو..."/><button className="primary" onClick={publish}>نشر الفيديو</button><button onClick={live}><Radio/> بث مباشر</button>{msg&&<p>{msg}</p>}</div></section>}
function Profile({session,auth}){return <section className="page center"><div className="avatar">L</div><h1>{session?'حسابك':'كن صانع محتوى على Lking'}</h1><p>{session?session.user.email:'انشر، ابنِ جمهورك وشارك في البث المباشر.'}</p>{!session&&<button className="primary" onClick={auth}>إنشاء حساب</button>}<div className="pitch"><Users/><div><b>برنامج صناع المحتوى</b><small>تحديات ومكافآت وفرص لتحقيق الدخل.</small></div></div></section>}
function Auth({close,done}){const [signup,setSignup]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[msg,setMsg]=useState('');const go=async()=>{const r=signup?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});if(r.error)setMsg(r.error.message);else if(r.data.session)done(r.data.session);else setMsg('تحقق من بريدك الإلكتروني.')};return <Modal close={close}><h2>{signup?'إنشاء حساب':'تسجيل الدخول'}</h2><input placeholder="البريد الإلكتروني" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="كلمة المرور" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button className="primary" onClick={go}>{signup?'إنشاء الحساب':'دخول'}</button><p>{msg}</p><button className="link" onClick={()=>setSignup(!signup)}>{signup?'لدي حساب':'إنشاء حساب جديد'}</button></Modal>}
function Broadcaster({session,close}){const ref=useRef(null),[title,setTitle]=useState('بث Lking'),[started,setStarted]=useState(false),stream=useRef(null);const start=async()=>{const {error}=await supabase.from('live_rooms').insert({host_id:session.user.id,title,status:'live'});if(error)return alert(error.message);stream.current=await navigator.mediaDevices.getUserMedia({video:true,audio:true});ref.current.srcObject=stream.current;setStarted(true)};useEffect(()=>()=>stream.current?.getTracks().forEach(t=>t.stop()),[]);return <Modal close={close}><h2>ابدأ بثك الآن</h2>{started?<video className="camera" ref={ref} autoPlay muted playsInline/>:<><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="عنوان البث"/><button className="primary" onClick={start}><Radio/> تشغيل الكاميرا والمايك</button></>}</Modal>}
function Studio({close}){return <Modal close={close}><h2>Creator Studio</h2><div className="stats"><div><BarChart3/><b>0</b><small>مشاهدات</small></div><div><Users/><b>0</b><small>متابعون</small></div><div><Gift/><b>500</b><small>مكافآت البداية</small></div></div><p>برنامج صناع المحتوى جاهز لإضافة التحديات والمكافآت وتحقيق الدخل بعد تفعيل أنظمة الدفع والحماية.</p></Modal>}
function Modal({children,close}){return <div className="modal"><div className="modal-box"><button className="close" onClick={close}><X/></button>{children}</div></div>}

createRoot(document.getElementById('root')).render(<App/>);
